repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.0.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args:
    - build       # changes of the build system or dependencies
    - change      # commit alters the implementation of an existing feature
    - chore       # technical or maintenance task not related to feature or user story
    - ci          # edits to the continuous integration scripts/configuration
    - deprecate   # a feature or functionality will be deprecated
    - docs        # add, update of revise the documentation
    - feat        # a new feature was implemented (bump MINOR version)
    - fix         # an issue or bug has been fixed (bump PATCH version)
    - perf        # performance improvements that do not alter existing behaviour
    - refactor    # update shuffles code around but does not alter functionality
    - remove      # a feature or functionality is removed
    - style       # source code is improved w.r.t. its code quality
    - test        # commits enhance or add to the test suite
    - merge       # merge one branch into another. Should be ignored by git-chglog
    - revert      # revert previous commit(s). Should be ignored by git-chglog
